"""Federated learning clients.

Clients ``i = 1, ..., n`` produce local updates ``Delta_{t,i}``.  Byzantine
clients ``B subset {1,...,n}`` may submit arbitrary ``Delta_{t,i}``.

THREAT MODEL (this is the fix for audit finding F6).
--------------------------------------------------
The previous version of this file generated Byzantine updates as fresh
zero-mean Gaussian noise::

    delta[name] = -torch.randn_like(param) * 0.01 * scale

That is not an attack.  It does not depend on the honest updates, on the
model, or on the task; two "coordinated" attackers had cosine similarity
around ``-0.007``; and in the shipped logs it *raised* FedAvg accuracy from
0.84 to 0.9225, because averaging in independent zero-mean noise is a mild
regulariser.

The rebuilt threat model is the standard **omniscient Byzantine** model used
by Xie et al. (2020) and Baruch et al. (2019): the adversary observes the
honest clients' updates for the current round before choosing its own.  The
server therefore collects honest updates first and only then asks the
Byzantine clients for theirs.  Concretely:

* :class:`BenignClient` runs local SGD and returns ``theta_local - theta_global``.
* :class:`ByzantineClient` wraps a :class:`~sca.experiments.attacks.ByzantineAttack`
  and **requires** ``benign_deltas``.  Calling it without them raises.

Two extra hooks exist because real attacks need them:

* ``honest_delta``   -- the update this attacker *would* have sent if honest.
  ``sign_flip`` negates exactly this, so the attack is a function of the
  attacker's real gradient rather than of fresh noise.
* ``poisoned_delta`` -- the update obtained by running the same local SGD on
  relabelled data.  The targeted safety-degradation attack uses this.
"""

from __future__ import annotations

import copy
from abc import ABC, abstractmethod
from dataclasses import dataclass
from typing import Any, Callable, Mapping, Sequence

import torch
import torch.nn as nn
from torch.utils.data import DataLoader

__all__ = [
    "ClientUpdate",
    "FLClient",
    "BenignClient",
    "ByzantineClient",
    "local_sgd",
    "flatten_delta",
    "delta_norm",
    "scale_delta",
    "MissingBenignDeltasError",
]


class MissingBenignDeltasError(ValueError):
    """Raised when a Byzantine client is asked for an update with no benign context.

    Existence of this error is the enforcement mechanism for the API rule
    "every attack takes ``benign_deltas`` as a REQUIRED argument".
    """


# ---------------------------------------------------------------------------
# Update container and tensor helpers
# ---------------------------------------------------------------------------


@dataclass
class ClientUpdate:
    """A client's local update ``Delta_{t,i}``.

    Attributes:
        client_id: Client identifier.
        delta: Parameter update, keyed exactly like ``model.named_parameters()``.
        n_samples: Number of local training samples used (0 for clients that
            do not train, e.g. pure model-poisoning attackers).
        is_byzantine: Ground-truth adversary flag.  Used ONLY for diagnostics
            and for post-hoc analysis; no aggregator is allowed to read it.
        metadata: Free-form auditing metadata.
    """

    client_id: int
    delta: dict[str, torch.Tensor]
    n_samples: int = 0
    is_byzantine: bool = False
    metadata: dict[str, Any] | None = None


def flatten_delta(
    delta: Mapping[str, torch.Tensor],
    keys: Sequence[str] | None = None,
) -> torch.Tensor:
    """Flatten a parameter dict into a single 1-D tensor in a fixed key order.

    Args:
        delta: Parameter dict.
        keys: Explicit key order.  Defaults to ``sorted(delta)`` so that two
            dicts with the same keys always flatten compatibly.
    """
    if keys is None:
        keys = sorted(delta)
    parts = [delta[k].reshape(-1).to(torch.float64) for k in keys]
    if not parts:
        return torch.zeros(0, dtype=torch.float64)
    return torch.cat(parts)


def delta_norm(delta: Mapping[str, torch.Tensor]) -> float:
    """L2 norm of the flattened update."""
    return float(flatten_delta(delta).norm().item())


def scale_delta(
    delta: Mapping[str, torch.Tensor], factor: float
) -> dict[str, torch.Tensor]:
    """Return a new dict with every tensor multiplied by ``factor``."""
    return {name: value * factor for name, value in delta.items()}


# ---------------------------------------------------------------------------
# Local training
# ---------------------------------------------------------------------------


def local_sgd(
    global_model: nn.Module,
    dataset: Any,
    *,
    lr: float = 0.05,
    local_epochs: int = 1,
    batch_size: int = 32,
    seed: int = 0,
    momentum: float = 0.0,
    weight_decay: float = 0.0,
    max_grad_norm: float | None = None,
    label_map: Callable[[torch.Tensor], torch.Tensor] | None = None,
) -> tuple[dict[str, torch.Tensor], int]:
    """Run local SGD from ``global_model`` and return ``(delta, n_samples)``.

    ``delta = theta_local - theta_global``.  The global model is never
    mutated -- training happens on a deep copy.

    Determinism: shuffling uses a ``torch.Generator`` seeded from ``seed``, so
    the result depends only on ``(seed, dataset, model, hyper-parameters)`` and
    not on the ambient global RNG state.  No Python ``hash()`` is involved
    anywhere (finding F9).

    Args:
        global_model: Current global model.
        dataset: A ``Dataset`` yielding ``(inputs, targets)``, or a ready
            ``DataLoader``.
        lr, local_epochs, batch_size, momentum, weight_decay: SGD settings.
        max_grad_norm: Optional gradient-norm clip.
        label_map: Optional relabelling applied to each target batch.  This is
            how data-poisoning attacks are expressed -- they change the labels,
            not the optimiser.
        seed: Seed for the shuffling generator.

    Returns:
        ``(delta, n_samples)``.
    """
    local_model = copy.deepcopy(global_model)
    local_model.train()

    init_params = {
        name: param.detach().clone()
        for name, param in local_model.named_parameters()
    }

    optimizer = torch.optim.SGD(
        local_model.parameters(),
        lr=lr,
        momentum=momentum,
        weight_decay=weight_decay,
    )

    if isinstance(dataset, DataLoader):
        loader = dataset
    else:
        generator = torch.Generator()
        generator.manual_seed(int(seed) % (2**63 - 1))
        loader = DataLoader(
            dataset,
            batch_size=batch_size,
            shuffle=True,
            generator=generator,
            drop_last=False,
        )

    n_samples = 0
    for _ in range(local_epochs):
        for batch in loader:
            if isinstance(batch, (tuple, list)):
                inputs, targets = batch[0], batch[1]
            else:
                inputs, targets = batch, batch
            if label_map is not None:
                targets = label_map(targets)
            optimizer.zero_grad()
            outputs = local_model(inputs)
            loss = nn.functional.cross_entropy(outputs, targets)
            loss.backward()
            if max_grad_norm is not None:
                torch.nn.utils.clip_grad_norm_(
                    local_model.parameters(), max_grad_norm
                )
            optimizer.step()
            n_samples += int(inputs.size(0))

    delta = {
        name: (param.detach() - init_params[name]).clone()
        for name, param in local_model.named_parameters()
    }
    return delta, n_samples


# ---------------------------------------------------------------------------
# Clients
# ---------------------------------------------------------------------------


class FLClient(ABC):
    """Abstract base class for federated learning clients."""

    #: Ground truth flag; never read by an aggregator.
    is_byzantine: bool = False

    def __init__(self, client_id: int) -> None:
        self.client_id = client_id

    @abstractmethod
    def compute_update(
        self,
        global_model: nn.Module,
        round_num: int,
        **kwargs: Any,
    ) -> ClientUpdate:
        """Compute this client's update for round ``round_num``."""


class BenignClient(FLClient):
    """Honest client performing local SGD on private data."""

    is_byzantine = False

    def __init__(
        self,
        client_id: int,
        dataset: Any,
        local_epochs: int = 1,
        lr: float = 0.05,
        batch_size: int = 32,
        seed: int = 0,
        momentum: float = 0.0,
        weight_decay: float = 0.0,
        max_grad_norm: float | None = None,
    ) -> None:
        super().__init__(client_id)
        self.dataset = dataset
        self.local_epochs = local_epochs
        self.lr = lr
        self.batch_size = batch_size
        self.seed = seed
        self.momentum = momentum
        self.weight_decay = weight_decay
        self.max_grad_norm = max_grad_norm

    def _sgd(
        self,
        global_model: nn.Module,
        round_num: int,
        label_map: Callable[[torch.Tensor], torch.Tensor] | None = None,
    ) -> tuple[dict[str, torch.Tensor], int]:
        return local_sgd(
            global_model,
            self.dataset,
            lr=self.lr,
            local_epochs=self.local_epochs,
            batch_size=self.batch_size,
            seed=self.seed + 1_000_003 * round_num + 7919 * self.client_id,
            momentum=self.momentum,
            weight_decay=self.weight_decay,
            max_grad_norm=self.max_grad_norm,
            label_map=label_map,
        )

    def compute_update(
        self,
        global_model: nn.Module,
        round_num: int,
        **kwargs: Any,
    ) -> ClientUpdate:
        delta, n_samples = self._sgd(global_model, round_num)
        return ClientUpdate(
            client_id=self.client_id,
            delta=delta,
            n_samples=n_samples,
            is_byzantine=False,
        )


class ByzantineClient(FLClient):
    """Adversarial client that crafts its update from the honest updates.

    The attack itself lives in :mod:`sca.experiments.attacks`.  This class is
    only the plumbing that supplies an attack with the three things a real
    attack needs: the round's honest updates, this attacker's own honest
    update, and (for data poisoning) its own poisoned update.

    ``compute_update`` REQUIRES ``benign_deltas``.  Omitting them raises
    :class:`MissingBenignDeltasError` rather than silently producing noise --
    that silent fallback is precisely finding F6.
    """

    is_byzantine = True

    def __init__(
        self,
        client_id: int,
        attack: "Any",
        dataset: Any | None = None,
        local_epochs: int = 1,
        lr: float = 0.05,
        batch_size: int = 32,
        seed: int = 0,
        momentum: float = 0.0,
        weight_decay: float = 0.0,
        max_grad_norm: float | None = None,
        poison_label_map: Callable[[torch.Tensor], torch.Tensor] | None = None,
        claimed_n_samples: int | None = None,
    ) -> None:
        """
        Args:
            client_id: Client identifier.
            attack: A :class:`~sca.experiments.attacks.ByzantineAttack`.
            dataset: The attacker's local data.  Required for any attack whose
                ``requires_honest_delta`` or ``requires_poisoned_delta`` is
                True (sign-flip and targeted poisoning).
            poison_label_map: Relabelling used to build ``poisoned_delta``.
                Defaults to the attack's own ``default_label_map`` when it has
                one.
            claimed_n_samples: The sample count the attacker REPORTS to the
                server.  ``None`` means "claim the median of the honest
                counts", which is the right default: an adversary that
                honestly reports ``0`` is silently down-weighted to nothing by
                sample-weighted FedAvg, which makes any attack look harmless
                for a reason that has nothing to do with the defence.  A real
                adversary lies about this number, so the simulator must let it.
            Remaining args: local SGD settings, as for :class:`BenignClient`.
        """
        super().__init__(client_id)
        self.attack = attack
        self.dataset = dataset
        self.local_epochs = local_epochs
        self.lr = lr
        self.batch_size = batch_size
        self.seed = seed
        self.momentum = momentum
        self.weight_decay = weight_decay
        self.max_grad_norm = max_grad_norm
        self.poison_label_map = poison_label_map
        self.claimed_n_samples = claimed_n_samples

    # -- helpers ------------------------------------------------------------

    def _sgd(
        self,
        global_model: nn.Module,
        round_num: int,
        label_map: Callable[[torch.Tensor], torch.Tensor] | None,
        stream: int,
    ) -> tuple[dict[str, torch.Tensor], int]:
        return local_sgd(
            global_model,
            self.dataset,
            lr=self.lr,
            local_epochs=self.local_epochs,
            batch_size=self.batch_size,
            seed=(
                self.seed
                + 1_000_003 * round_num
                + 7919 * self.client_id
                + 104_729 * stream
            ),
            momentum=self.momentum,
            weight_decay=self.weight_decay,
            max_grad_norm=self.max_grad_norm,
            label_map=label_map,
        )

    def honest_delta(
        self, global_model: nn.Module, round_num: int
    ) -> tuple[dict[str, torch.Tensor], int]:
        """The update this attacker would have sent if it were honest."""
        if self.dataset is None:
            raise ValueError(
                f"Client {self.client_id}: attack "
                f"{getattr(self.attack, 'name', self.attack)!r} needs the "
                "attacker's own honest update, so a dataset is required."
            )
        return self._sgd(global_model, round_num, None, stream=0)

    def poisoned_delta(
        self, global_model: nn.Module, round_num: int
    ) -> tuple[dict[str, torch.Tensor], int]:
        """The update obtained by training on relabelled (poisoned) data."""
        if self.dataset is None:
            raise ValueError(
                f"Client {self.client_id}: attack "
                f"{getattr(self.attack, 'name', self.attack)!r} is a data "
                "poisoning attack and requires a dataset."
            )
        label_map = self.poison_label_map or getattr(
            self.attack, "default_label_map", None
        )
        if label_map is None:
            raise ValueError(
                f"Client {self.client_id}: no poison_label_map supplied and "
                f"attack {getattr(self.attack, 'name', self.attack)!r} has no "
                "default_label_map."
            )
        return self._sgd(global_model, round_num, label_map, stream=1)

    # -- main entry point ---------------------------------------------------

    def compute_update(
        self,
        global_model: nn.Module,
        round_num: int,
        benign_deltas: Sequence[Mapping[str, torch.Tensor]] | None = None,
        attacker_index: int = 0,
        n_attackers: int = 1,
        benign_n_samples: Sequence[int] | None = None,
        **kwargs: Any,
    ) -> ClientUpdate:
        """Craft the adversarial update.

        Args:
            global_model: Current global model.
            round_num: FL round index (1-based).
            benign_deltas: The honest clients' updates for THIS round.
                REQUIRED -- see :class:`MissingBenignDeltasError`.
            attacker_index: This attacker's index within the colluding group.
            n_attackers: Size of the colluding group.
            benign_n_samples: The honest clients' reported sample counts, used
                to pick a plausible lie for this attacker's own count.
        """
        # Local import keeps sca.federated free of a hard dependency on the
        # experiments package at import time.
        from sca.experiments.attacks import AttackContext

        if benign_deltas is None or len(benign_deltas) == 0:
            raise MissingBenignDeltasError(
                f"Client {self.client_id}: benign_deltas is a required "
                "argument for every Byzantine attack. Passing None/empty is "
                "what made the old attack a model-independent noise generator "
                "(finding F6)."
            )

        honest, n_honest = (None, 0)
        if getattr(self.attack, "requires_honest_delta", False):
            honest, n_honest = self.honest_delta(global_model, round_num)

        poisoned, n_poison = (None, 0)
        if getattr(self.attack, "requires_poisoned_delta", False):
            poisoned, n_poison = self.poisoned_delta(global_model, round_num)

        context = AttackContext(
            honest_delta=honest,
            poisoned_delta=poisoned,
            global_model=global_model,
            round_num=round_num,
            attacker_index=attacker_index,
            n_attackers=n_attackers,
            client_id=self.client_id,
            seed=self.seed,
        )

        delta = self.attack.craft(list(benign_deltas), context)

        # An attacker reports whatever sample count it likes.  Reporting 0 (as
        # the old code effectively did) hands sample-weighted FedAvg a free
        # defence: the attacker's weight becomes ~1/N and no attack can do
        # anything. Claim the median honest count instead.
        n_samples = self.claimed_n_samples
        if n_samples is None:
            n_samples = max(n_honest, n_poison)
        if not n_samples and benign_n_samples:
            counts = sorted(int(c) for c in benign_n_samples)
            n_samples = counts[len(counts) // 2]
        n_samples = int(n_samples or 1)

        return ClientUpdate(
            client_id=self.client_id,
            delta=delta,
            n_samples=n_samples,
            is_byzantine=True,
            metadata={
                "attack": getattr(self.attack, "name", str(self.attack)),
                "round": round_num,
                "attacker_index": attacker_index,
                "n_attackers": n_attackers,
            },
        )
